export type Region = (typeof regions)[number];
export const runtimes = [
    'dotnet6',
    'dotnetcore1.0',
    'dotnetcore2.0',
    'dotnetcore2.1',
    'dotnetcore3.1',
    'go1.x',
    'java11',
    'java17',
    'java8',
    'java8.al2',
    'nodejs',
    'nodejs10.x',
    'nodejs12.x',
    'nodejs14.x',
    'nodejs16.x',
    'nodejs18.x',
    'nodejs4.3',
    'nodejs4.3-edge',
    'nodejs6.10',
    'nodejs8.10',
    'provided',
    'provided.al2',
    'python2.7',
    'python3.10',
    'python3.6',
    'python3.7',
    'python3.8',
    'python3.9',
    'ruby2.5',
    'ruby2.7',
] as const;

export const regions = [
    'us-east-2',
    'us-east-1',
    'us-west-1',
    'us-west-2',
    'af-south-1',
    'ap-east-1',
    'ap-south-2',
    'ap-southeast-3',
    'ap-southeast-4',
    'ap-south-1',
    'ap-northeast-3',
    'ap-northeast-2',
    'ap-southeast-1',
    'ap-southeast-2',
    'ap-northeast-1',
    'ca-central-1',
    'eu-central-1',
    'eu-west-1',
    'eu-west-2',
    'eu-south-1',
    'eu-west-3',
    'eu-south-2',
    'eu-north-1',
    'eu-central-2',
    'me-south-1',
    'me-central-1',
    'sa-east-1',
    'us-gov-east-1',
    'us-gov-west-1',
] as const;
